version: '3.8'

services:

  cpu-service:
    build: ./cpu-service
    ports:
      - "8081:8081"
    networks:
      - monitoring

  memory-service:
    build: ./memory-service
    ports:
      - "8082:8082"
    networks:
      - monitoring

  disk-service:
    build: ./disk-service
    ports:
      - "8083:8083"
    networks:
      - monitoring

  wifi-service:
    build: ./wifi-service
    ports:
      - "8084:8084"
    networks:
      - monitoring

  frontend-service:
    build: ./frontend-service
    ports:
      - "8080:80"  # Port 80 inside container served to host on 8080
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=false
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring

volumes:
  grafana-storage:

networks:
  monitoring:
